// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Premya.Api.Infrastructure.Persistence;

#nullable disable

namespace Premya.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PremyaDbContext))]
    [Migration("20260903082821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Premya.Api.Domain.Entities.DynamicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "RowNumber")
                        .IsUnique();

                    b.ToTable("DynamicRecords");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.DynamicValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DynamicRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileStructureFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileStructureFieldId");

                    b.HasIndex("DynamicRecordId", "FileStructureFieldId")
                        .IsUnique();

                    b.ToTable("DynamicValues");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileStructureVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetricFieldId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricFieldId");

                    b.HasIndex("FileStructureVersionId", "FieldName")
                        .IsUnique();

                    b.ToTable("FileStructureFields");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FileStructureVersions");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileStructureVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileStructureVersionId");

                    b.HasIndex("MetricId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremiumMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PremiumMethodId", "Name")
                        .IsUnique();

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.MetricField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId", "FieldName")
                        .IsUnique();

                    b.ToTable("MetricFields");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.PremiumMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PremiumRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MethodNumber")
                        .IsUnique();

                    b.ToTable("PremiumMethods");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.DynamicRecord", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("DynamicRecords")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.DynamicValue", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.DynamicRecord", "DynamicRecord")
                        .WithMany("DynamicValues")
                        .HasForeignKey("DynamicRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premya.Api.Domain.Entities.FileStructureField", "FileStructureField")
                        .WithMany("DynamicValues")
                        .HasForeignKey("FileStructureFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicRecord");

                    b.Navigation("FileStructureField");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureField", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.FileStructureVersion", "FileStructureVersion")
                        .WithMany("Fields")
                        .HasForeignKey("FileStructureVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premya.Api.Domain.Entities.MetricField", "MetricField")
                        .WithMany("FileStructureFields")
                        .HasForeignKey("MetricFieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FileStructureVersion");

                    b.Navigation("MetricField");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureVersion", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.Metric", "Metric")
                        .WithMany("FileStructureVersions")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.FileStructureVersion", "FileStructureVersion")
                        .WithMany("ImportBatches")
                        .HasForeignKey("FileStructureVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premya.Api.Domain.Entities.Metric", "Metric")
                        .WithMany("ImportBatches")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileStructureVersion");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.Metric", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.PremiumMethod", "PremiumMethod")
                        .WithMany("Metrics")
                        .HasForeignKey("PremiumMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PremiumMethod");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.MetricField", b =>
                {
                    b.HasOne("Premya.Api.Domain.Entities.Metric", "Metric")
                        .WithMany("MetricFields")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.DynamicRecord", b =>
                {
                    b.Navigation("DynamicValues");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureField", b =>
                {
                    b.Navigation("DynamicValues");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.FileStructureVersion", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("ImportBatches");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("DynamicRecords");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.Metric", b =>
                {
                    b.Navigation("FileStructureVersions");

                    b.Navigation("ImportBatches");

                    b.Navigation("MetricFields");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.MetricField", b =>
                {
                    b.Navigation("FileStructureFields");
                });

            modelBuilder.Entity("Premya.Api.Domain.Entities.PremiumMethod", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
